version: '2'

services:
  peer1org3.org3.example.com:
    container_name: peer1org3.org3.example.com
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_PEER_ID=peer1org3.org3.example.com
      - CORE_PEER_ADDRESS=peer1org3.org3.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1org3.org3.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1org3.org3.example.com:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1org3.org3.example.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=info
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1org3.org3.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1org3.org3.example.com/tls:/etc/hyperledger/fabric/tls
    networks:
      - mynetwork

networks:
  mynetwork:
    external:
      name: myfabricnetwork
