---
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer1org1

    Users:
      - Name: Admin
        Secret: adminpw

  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer1org2

    Users:
      - Name: Admin
        Secret: adminpw

  - Name: Org3
    Domain: org3.example.com
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer1org3

    Users:
      - Name: Admin
        Secret: adminpw

  - Name: Org4
    Domain: org4.example.com
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer1org4

    Users:
      - Name: Admin
        Secret: adminpw

